
version: 2

models:
  - name: fct_vendas
    description: "Tabela fato centralizada no grão do item do pedido. Armazena o histórico completo de transações e métricas calculadas de faturamento bruto e líquido."
    columns:
      - name: pk_id_detalhe_pedido
        description: "Chave primária e grão da tabela fato (Identificador do item na linha do pedido)."
        tests:
          - unique
          - not_null
      - name: fk_id_pedido
        description: "Chave estrangeira / Código identificador do pedido macro (Cabeçalho)."
      - name: fk_id_produto
        description: "Chave estrangeira que conecta com a dim_produtos."
      - name: fk_id_cliente
        description: "Chave estrangeira que conecta com a dim_clientes."
      - name: fk_id_cartao_credito
        description: "Chave estrangeira que conecta com a dim_cartoes_credito."
      - name: fk_id_endereco
        description: "Chave estrangeira que conecta com a dim_localizacoes."
      - name: data_pedido
        description: "Data em que a venda foi realizada (Chave de tempo para análises cronológicas)."
      - name: status_pedido
        description: "Código do status atual do pedido (ex: 5 = Concluído)."
      - name: is_venda_online
        description: "Flag booleano indicando se a venda foi realizada pelo e-commerce (True) ou via vendedor físico (False)."
      - name: motivos_venda
        description: "Motivos associados à compra unificados em string (ex: 'On Promotion, Price') evitando duplicação de linhas."
      - name: quantidade_item
        description: "Quantidade física de unidades compradas daquele item."
      - name: preco_unitario
        description: "Preço de venda praticado para o produto na data da compra."
      - name: percentual_desconto_item
        description: "Percentual de desconto concedido sobre o preço unitário do item."
      - name: valor_bruto_item
        description: "Métrica calculada: Faturamento bruto da linha (Quantidade * Preço Unitário)."
      - name: valor_desconto_item
        description: "Métrica calculada: Valor absoluto em dinheiro deduzido pelo desconto da linha."
      - name: valor_liquido_item
        description: "Métrica calculada: Faturamento líquido real da linha após desconto aplicado."

  - name: dim_produtos
    description: "Dimensão que consolida a árvore completa de produtos comercializáveis, suas subcategorias e categorias macro."
    columns:
      - name: pk_id_produto
        description: "Chave primária do produto (SKU único)."
        tests:
          - unique
          - not_null
      - name: nome_produto
        description: "Nome comercial do produto."
      - name: codigo_produto
        description: "Código identificador de fábrica do produto."
      - name: cor_produto
        description: "Cor descritiva do produto."
      - name: preco_lista
        description: "Preço de tabela sugerido pela fábrica."
      - name: subcategoria
        description: "Nome da subcategoria do produto (ex: Mountain Bikes)."
      - name: categoria
        description: "Nome da categoria macro do produto (ex: Bikes)."


  - name: dim_localizacoes
    description: "Dimensão geográfica que unifica o endereço, cidade, estado e país dos clientes."
    columns:
      - name: pk_id_endereco
        description: "Chave primária do endereço usada para conectar com a fct_vendas."
        tests:
          - unique
          - not_null
      - name: endereco
        description: "Logradouro completo combinado (Rua, número, complemento)."
      - name: cidade
        description: "Nome da cidade do endereço de cobrança."
      - name: codigo_postal
        description: "Código postal / CEP do endereço."
      - name: estado
        description: "Nome completo do Estado ou Província."
      - name: sigla_estado
        description: "Sigla ou código do Estado (ex: SP, NY)."
      - name: pais
        description: "Nome completo do País de destino."

  - name: dim_clientes
    description: "Dimensão de clientes que unifica o identificador de vendas ao nome real de pessoas físicas ou registro de lojas."
    columns:
      - name: pk_id_cliente
        description: "Chave primária do cliente no ecossistema de vendas."
        tests:
          - unique
          - not_null
      - name: nome_cliente
        description: "Nome completo do cliente ou Razão Social da loja."
      - name: tipo_cliente
        description: "Tipo de cliente cadastrado (Pessoa Física ou Pessoa Jurídica)."
      - name: fk_id_loja
        description: "Código identificador da loja (se aplicável)."
      - name: fk_id_territorio
        description: "Código do território geográfico interno associado ao cliente."

  - name: dim_cartoes_credito
    description: "Dimensão analítica dos cartões de crédito utilizados como meio de pagamento."
    columns:
      - name: pk_id_cartao_credito
        description: "Chave primária do cartão de crédito."
        tests:
          - unique
          - not_null
      - name: tipo_cartao
        description: "Bandeira do cartão de crédito (ex: Vista, SuperiorCard)."
      - name: numero_cartao_credito
        description: "Número do cartão de crédito mascarado/armazenado."
      - name: mes_vencimento_cartao
        description: "Mês de expiração da validade do cartão."
      - name: ano_vencimento_cartao
        description: "Ano de expiração da validade do cartão."